"""init

Revision ID: 43fca35fcc9c
Revises: 
Create Date: 2026-08-14 08:50:47.430404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43fca35fcc9c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('department_name', sa.String(length=120), nullable=True),
    sa.Column('assigned_by', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_user_id'), 'admins', ['user_id'], unique=True)
    op.create_table('notification_schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('times_per_day', sa.Integer(), nullable=False),
    sa.Column('times_list', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('templates', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('route_data', sa.JSON(), nullable=True),
    sa.Column('read_by', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_otps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_otps_phone'), 'phone_otps', ['phone'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('commission_rate', sa.Integer(), nullable=False),
    sa.Column('surge_multiplier', sa.Float(), nullable=False),
    sa.Column('minimum_withdrawal', sa.Integer(), nullable=False),
    sa.Column('topup_promo_active', sa.Boolean(), nullable=False),
    sa.Column('topup_promo_rate', sa.Integer(), nullable=False),
    sa.Column('class_rates', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('slang_mode', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('admin_role', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('driver_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=30), nullable=False),
    sa.Column('vehicle_model', sa.String(length=120), nullable=True),
    sa.Column('vehicle_color', sa.String(length=60), nullable=True),
    sa.Column('vehicle_plate', sa.String(length=30), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('kyc_status', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('kyc_documents', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('cnic_number', sa.String(length=50), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_profiles_user_id'), 'driver_profiles', ['user_id'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payment_type', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('paid_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('redirect_url', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('ride_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ride_id', sa.String(), nullable=True),
    sa.Column('pickup_name', sa.String(length=255), nullable=False),
    sa.Column('dest_name', sa.String(length=255), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lng', sa.Float(), nullable=True),
    sa.Column('dest_lat', sa.Float(), nullable=True),
    sa.Column('dest_lng', sa.Float(), nullable=True),
    sa.Column('fare', sa.Integer(), nullable=False),
    sa.Column('tip_amount', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('vehicle_class', sa.String(length=30), nullable=False),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('points_redeemed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_history_user_id'), 'ride_history', ['user_id'], unique=False)
    op.create_table('rides',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('passenger_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=True),
    sa.Column('passenger_name', sa.String(length=255), nullable=True),
    sa.Column('passenger_phone', sa.String(length=20), nullable=True),
    sa.Column('pickup', sa.JSON(), nullable=False),
    sa.Column('destination', sa.JSON(), nullable=False),
    sa.Column('ride_class_id', sa.String(length=30), nullable=False),
    sa.Column('fare', sa.Integer(), nullable=False),
    sa.Column('base_fare', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('surge_multiplier', sa.Float(), nullable=False),
    sa.Column('waiting_fare', sa.Integer(), nullable=False),
    sa.Column('tip_amount', sa.Integer(), nullable=False),
    sa.Column('points_redeemed', sa.Integer(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('commission_rate', sa.Integer(), nullable=False),
    sa.Column('platform_commission', sa.Integer(), nullable=False),
    sa.Column('driver_net_earnings', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('cancel_reason', sa.String(length=40), nullable=True),
    sa.Column('cancelled_by', sa.String(length=20), nullable=True),
    sa.Column('waiting_time_seconds', sa.Integer(), nullable=False),
    sa.Column('passenger_rating', sa.Integer(), nullable=True),
    sa.Column('passenger_praise', sa.String(), nullable=True),
    sa.Column('payment_transaction_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rides_driver_id'), 'rides', ['driver_id'], unique=False)
    op.create_index(op.f('ix_rides_passenger_id'), 'rides', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_rides_status'), 'rides', ['status'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    op.create_table('payment_installments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('payer_user_id', sa.String(), nullable=True),
    sa.Column('payer_phone', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_transaction_id', sa.String(), nullable=True),
    sa.Column('payment_url', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_installments_payment_id'), 'payment_installments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_installments_provider_transaction_id'), 'payment_installments', ['provider_transaction_id'], unique=True)
    op.create_table('ride_chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ride_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=True),
    sa.Column('sender_role', sa.String(length=20), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_chat_messages_ride_id'), 'ride_chat_messages', ['ride_id'], unique=False)
    op.create_table('ride_location_updates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ride_id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_location_updates_ride_id'), 'ride_location_updates', ['ride_id'], unique=False)
    op.create_table('ride_share_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ride_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_share_tokens_ride_id'), 'ride_share_tokens', ['ride_id'], unique=False)
    op.create_index(op.f('ix_ride_share_tokens_token'), 'ride_share_tokens', ['token'], unique=True)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('bonus_amount', sa.Integer(), nullable=False),
    sa.Column('tip_amount', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('carrier', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ride_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_user_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_ride_share_tokens_token'), table_name='ride_share_tokens')
    op.drop_index(op.f('ix_ride_share_tokens_ride_id'), table_name='ride_share_tokens')
    op.drop_table('ride_share_tokens')
    op.drop_index(op.f('ix_ride_location_updates_ride_id'), table_name='ride_location_updates')
    op.drop_table('ride_location_updates')
    op.drop_index(op.f('ix_ride_chat_messages_ride_id'), table_name='ride_chat_messages')
    op.drop_table('ride_chat_messages')
    op.drop_index(op.f('ix_payment_installments_provider_transaction_id'), table_name='payment_installments')
    op.drop_index(op.f('ix_payment_installments_payment_id'), table_name='payment_installments')
    op.drop_table('payment_installments')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_rides_status'), table_name='rides')
    op.drop_index(op.f('ix_rides_passenger_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_driver_id'), table_name='rides')
    op.drop_table('rides')
    op.drop_index(op.f('ix_ride_history_user_id'), table_name='ride_history')
    op.drop_table('ride_history')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_driver_profiles_user_id'), table_name='driver_profiles')
    op.drop_table('driver_profiles')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_phone_otps_phone'), table_name='phone_otps')
    op.drop_table('phone_otps')
    op.drop_table('notifications')
    op.drop_table('notification_schedules')
    op.drop_index(op.f('ix_admins_user_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
